name: Publish zip

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Publish datapack zip
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
    - uses: actions/checkout@v4

    - name: Build
      run: |
        git archive --format zip -o ./datapack.zip ${{ github.ref }}

    - name: Upload zip to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.ref }}
        file: ./datapack.zip
        asset_name: UndyingPets-$tag.zip
